import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/ui/navbar";
import { Shantell_Sans } from "next/font/google";
 const shantell = Shantell_Sans({ subsets: ["latin"] });
 import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shantell.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
   <Navbar/>
   {children}
          </ThemeProvider>
     
        </body>
    </html>
  );
}
